name: gcloud

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  gcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/setup-kubectl@v3.2

    - uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/30098225237/locations/global/workloadIdentityPools/gha-pool/providers/gha-provider'
        service_account: 'gha-sa@imjasonh-autopilot.iam.gserviceaccount.com'

    - uses: 'google-github-actions/setup-gcloud@v0'
      with:
        project_id: imjasonh-autopilot
    - run: |
        gcloud container clusters get-credentials autopilot \
            --region us-east1

    - run: kubectl get pods
